oldLighting=false
separateAo=false
oldHandLight=false

shadowEntities=false
shadowBlockEntities=false
shadowPlayer=false

shadowDistance=0.0

particles.ordering=after

rain.depth=false
beacon.beam.depth=false
clouds.depth=false

occlusion.culling=true
bufferFormat.colortex0=RGBA8